sylius_grid:
    grids:
        monsieurbiz_cms_page:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_cms_page.model.page.class%'
            limits: [25, 50, 100, 200]
            fields:
                code:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.code
                    sortable: ~
                title:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.title
                    sortable: translation.title
                enabled:
                    type: twig
                    label: monsieurbiz_cms_page.ui.form.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                        label: monsieurbiz_cms_page.ui.actions.create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                code:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.code
                title:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.title
                enabled:
                    type: boolean
                    label: monsieurbiz_cms_page.ui.form.enabled
                content:
                    type: boolean
                    label: monsieurbiz_cms_page.ui.form.content

        monsieurbiz_cms_block:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_cms_block.model.block.class%'
            limits: [25, 50, 100, 200]
            fields:
                title:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.title
                    sortable: ~
                code:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.code
                    sortable: ~
                enabled:
                    type: twig
                    label: monsieurbiz_cms_page.ui.form.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                        label: monsieurbiz_cms_page.ui.actions.create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                title:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.title
                code:
                    type: string
                    label: monsieurbiz_cms_page.ui.form.code
                enabled:
                    type: boolean
                    label: monsieurbiz_cms_page.ui.form.enabled
                content:
                    type: boolean
                    label: monsieurbiz_cms_page.ui.form.content
