sylius_resource:
    resources:
        monsieurbiz_cms_page.page:
            classes:
                model: MonsieurBiz\SyliusCmsPagePlugin\Entity\Page
                interface: MonsieurBiz\SyliusCmsPagePlugin\Entity\PageInterface
                form: MonsieurBiz\SyliusCmsPagePlugin\Form\Type\PageType
                repository: MonsieurBiz\SyliusCmsPagePlugin\Repository\PageRepository
            translation:
                classes:
                    model: MonsieurBiz\SyliusCmsPagePlugin\Entity\PageTranslation
                    interface: MonsieurBiz\SyliusCmsPagePlugin\Entity\PageTranslationInterface

        monsieurbiz_cms_block.block:
            classes:
                model: MonsieurBiz\SyliusCmsPagePlugin\Entity\Block
                interface: MonsieurBiz\SyliusCmsPagePlugin\Entity\BlockInterface
                form: MonsieurBiz\SyliusCmsPagePlugin\Form\Type\BlockType
                repository: MonsieurBiz\SyliusCmsPagePlugin\Repository\BlockRepository
            translation:
                classes:
                    model: MonsieurBiz\SyliusCmsPagePlugin\Entity\BlockTranslation
                    interface: MonsieurBiz\SyliusCmsPagePlugin\Entity\BlockTranslationInterface
